### PR TITLE
Issues 197,198,199resolved

### LINKED ISSUE #197: Email verified page
The html page in `views/email_verified.html` is displayed, when email of a user is verified. 

Currently it is just plain html.

Add css and improve page layout

### LINKED ISSUE #198: link expired page
`views/link_expired.html`

### LINKED ISSUE #199: password change form and reset successful page
`views/password-submission.html`

### PR DESCRIPTION
**Pull request by Saksham-Sharma-99**
just getting started!
Fixes #197 
Fixes #198 
Fixes #199 

Screenshot 2021-03-24 at 5 39 54 PM
_______________________________

Screenshot 2021-03-24 at 5 40 06 PM
_______________________________

Screenshot 2021-03-24 at 3 03 19 PM

### CODE REVIEW

**Comment by dev-ritik** [comment]
@Saksham-Sharma-99 add screenshots for UI changes

**Comment by Saksham-Sharma-99** [comment]
> @Saksham-Sharma-99 add screenshots for UI changes

done!

**Comment by Saksham-Sharma-99** [comment]
issue 199, 198 also done

**Comment by dev-ritik** [comment]
@Saksham-Sharma-99 rebase the latest commit to a different branch from master and then raise a new PR. PR must be concise and address a single (or similar) issue.

**Comment by Saksham-Sharma-99** [comment]
> @Saksham-Sharma-99 rebase the latest commit to a different branch from master and then raise a new PR. PR must be concise and address a single (or similar) issue.

Okay .

**Comment by Saksham-Sharma-99** [comment]
> @Saksham-Sharma-99 rebase the latest commit to a different branch from master and then raise a new PR. PR must be concise and address a single (or similar) issue.

Done :)

**Pull request closed without merging**
